name: gowapit_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  easy_localization: ^3.0.8
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.7
  image_picker: ^1.1.2
  lottie: ^3.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/peta_wapit.png
    - assets/data_pariwisata.json
    - assets/translations/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png" # <-- Pastikan jalur ini sama dengan letak logo Anda
  min_sdk_size: 21