// File generated by FlutterFire configuration / template for GoWapit
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCgMIBYuv0Wyrd3w5AOfImHUMFlf77nFF8",
    authDomain: "go-wapit-app.firebaseapp.com",
    projectId: "go-wapit-app",
    storageBucket: "go-wapit-app.firebasestorage.app",
    messagingSenderId: "817685661630",
    appId: "1:817685661630:web:fd7a9a4926500650c81bef",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLLeA-OsEjctHQ3wDFeTqERK6h6vP2PmA',
    appId: '1:817685661630:android:24ff9f0c89cb7ed9c81bef',
    messagingSenderId: '817685661630',
    projectId: 'go-wapit-app',
    storageBucket: 'go-wapit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_GoWapitDefaultIosApiKeyMock12345',
    appId: '1:568161780177:ios:com.example.gowapitFrontend',
    messagingSenderId: '568161780177',
    projectId: 'gowapit-app',
    storageBucket: 'gowapit-app.firebasestorage.app',
    iosBundleId: 'com.example.gowapitFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_GoWapitDefaultMacosApiKeyMock123',
    appId: '1:568161780177:ios:com.example.gowapitFrontend',
    messagingSenderId: '568161780177',
    projectId: 'gowapit-app',
    storageBucket: 'gowapit-app.firebasestorage.app',
    iosBundleId: 'com.example.gowapitFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_GoWapitDefaultWindowsApiKeyMock1',
    appId: '1:568161780177:web:gowapitappsparkwindows',
    messagingSenderId: '568161780177',
    projectId: 'gowapit-app',
    authDomain: 'gowapit-app.firebaseapp.com',
    storageBucket: 'gowapit-app.firebasestorage.app',
  );
}
